import { config } from "./config";

function esc(value: string) { return value.replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]!)); }

export function feeEmail(input: {studentNames:string[];month:string;amount:string;currency:string;payUrl:string}) {
  const students = input.studentNames.map(esc).join(", ");
  return `<!doctype html><html><body style="margin:0;background:#f5f7fb;font-family:Arial,sans-serif;color:#12203a"><div style="max-width:680px;margin:30px auto;background:#fff;border:1px solid #e8edf5;border-radius:24px;overflow:hidden"><div style="padding:32px;background:#071f49;color:#fff"><div style="font-size:12px;letter-spacing:2px;font-weight:800">GLOBAL PUNJABI CLASSES</div><h1 style="margin:12px 0 0;font-size:28px">Monthly Fee Payment</h1></div><div style="padding:34px"><p><b>Sat Shri Akal Ji</b></p><p>This is to inform you that the monthly fee for <b>${students}</b> at Global Punjabi Classes is due for <b>${esc(input.month)}</b>.</p><div style="background:#f6f8fc;border-radius:18px;padding:22px;margin:24px 0"><div style="font-size:12px;color:#64748b">FEE AMOUNT</div><div style="font-size:32px;font-weight:800;color:#071f49;margin-top:6px">${esc(input.currency)} ${esc(input.amount)}</div></div><p>Kindly use the secure payment link below to complete the payment:</p><p><a href="${esc(input.payUrl)}" style="display:inline-block;background:#d69a1d;color:#fff;text-decoration:none;padding:15px 22px;border-radius:12px;font-weight:800">PAY MONTHLY FEE</a></p><p style="color:#64748b">The payment page provides the available payment methods and complete payment instructions. Once the payment has been successfully received and verified, the payment status will be updated and the receipt/invoice will be issued accordingly.</p><p>Thank you for your continued support of Global Punjabi Classes.</p><p>Regards,<br><b>Global Punjabi Classes</b><br>${esc(config.businessEmail)}</p></div></div></body></html>`;
}

export function feeWhatsAppPreview(input:{studentNames:string[];month:string;amount:string;currency:string;payUrl:string}) {
  return `Sat Shri Akal Ji\n\nThis is to inform you that the monthly fee for ${input.studentNames.join(", ")} at Global Punjabi Classes is due for ${input.month}.\n\nStudent: ${input.studentNames.join(", ")}\nMonthly Fee: ${input.currency} ${input.amount}\nFee Period: ${input.month}\n\nKindly use the secure payment link below to complete the payment:\n${input.payUrl}\n\nOnce the payment has been successfully received and verified, the payment status will be updated and the receipt/invoice will be issued accordingly.\n\nThank you for your continued support of Global Punjabi Classes.\n\nRegards,\nGlobal Punjabi Classes`;
}
